### ISSUE TITLE
Failing to build on Kinetic

### ISSUE THREAD

**Issue by tfoote** [SCU-RSL-ROS/radar_omnipresense#10]
The build of this package is failing on all architectures for Kinetic due to what appears to be a missing dependency. 

For example: http://build.ros.org/view/Kbin_uX64/job/Kbin_uX64__radar_omnipresense__ubuntu_xenial_amd64__binary/81/console
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
RapidJSON_INCLUDE_DIRS
```

**Comment by omnipresense** [comment]
Hi Tully,

Let me talk to Jim about it.

Rob

**Comment by jimwhitfield** [comment]
Fix pending on my collaborator access to radar_omnipresense-release

**Comment by jimwhitfield** [comment]
I believe this is resolved.  Please reopen if necessary.
