### ISSUE TITLE
New Melodic release

### ISSUE THREAD

**Issue by clalancette** [SCU-RSL-ROS/radar_omnipresense#9]
radar_omnipresence has been failing to build in Melodic for some time (example: http://build.ros.org/view/Mbin_ds_dS64/job/Mbin_ds_dS64__radar_omnipresense__debian_stretch_amd64__binary/38/consoleFull).  I see that the initial problem with that was fixed in c2ea34cbf07f33508ae41352e3eaeec26c95f7c4, which is fantastic!  Could we get another release into Melodic to try and make it build?  Thanks in advance.

**Comment by clalancette** [comment]
Ping?  Another release into Melodic would be appreciated.

**Comment by jimwhitfield** [comment]
I haven't heard from Garren.  I'll do this next week after I get back from
vacation. Sorry for the delay.
Jim

**Comment by clalancette** [comment]
> I haven't heard from Garren. I'll do this next week after I get back from vacation. Sorry for the delay.

No problem, thanks for the update.

**Comment by jimwhitfield** [comment]
Fix pending on my collaborator access to radar_omnipresense-release

**Comment by jimwhitfield** [comment]
Release branch checked in.

**Comment by jimwhitfield** [comment]
I believe this is resolved.  Please reopen if necessary.
